#!/usr/bin/env python3
"""
Download Bluetooth SIG assigned numbers and generate C++ lookup tables.

Sources:
  - Company Identifiers: https://bitbucket.org/bluetooth-SIG/public
  - AD Types: https://bitbucket.org/bluetooth-SIG/public

Usage:
    python3 scripts/generate_assigned_numbers.py

Outputs:
    src/assigned_numbers.cpp
"""

import urllib.request
import yaml
import os
import sys
from datetime import date

COMPANY_IDS_URL = (
    "https://bitbucket.org/bluetooth-SIG/public/raw/main/"
    "assigned_numbers/company_identifiers/company_identifiers.yaml"
)
AD_TYPES_URL = (
    "https://bitbucket.org/bluetooth-SIG/public/raw/main/"
    "assigned_numbers/core/ad_types.yaml"
)

OUTPUT_PATH = os.path.join(os.path.dirname(__file__), "..", "src", "assigned_numbers.cpp")


def download_yaml(url: str) -> dict:
    """Download and parse a YAML file from a URL."""
    print(f"Downloading {url}")
    with urllib.request.urlopen(url) as response:
        return yaml.safe_load(response.read())


def escape_cpp_string(s: str) -> str:
    """Escape a string for use in a C++ string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def generate_cpp(companies: list, ad_types: list) -> str:
    """Generate the C++ source file content."""
    lines = []
    lines.append(f"// Auto-generated by scripts/generate_assigned_numbers.py on {date.today()}")
    lines.append("// Source: Bluetooth SIG Assigned Numbers")
    lines.append("// Do not edit manually — re-run the generator to update.")
    lines.append("")
    lines.append("#include <ble_sniffer/assigned_numbers.h>")
    lines.append("")
    lines.append("namespace ble_sniffer {")
    lines.append("")

    # Company identifiers lookup
    lines.append("const char* company_name_from_id(uint16_t company_id) {")
    lines.append("    switch (company_id) {")
    for entry in companies:
        value = entry["value"]
        name = escape_cpp_string(entry["name"])
        lines.append(f'        case {value}: return "{name}";')
    lines.append('        default: return "Unknown";')
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # AD type lookup
    lines.append("const char* ad_type_name(uint8_t type) {")
    lines.append("    switch (type) {")
    seen_values = set()
    for entry in ad_types:
        value = entry["value"]
        if value in seen_values:
            continue  # skip duplicates (some values have multiple meanings)
        seen_values.add(value)
        name = escape_cpp_string(entry["name"])
        lines.append(f'        case {value}: return "{name}";')
    lines.append('        default: return "Unknown";')
    lines.append("    }")
    lines.append("}")
    lines.append("")
    lines.append("} // namespace ble_sniffer")
    lines.append("")

    return "\n".join(lines)


def main():
    print("Fetching Bluetooth SIG assigned numbers...")

    company_data = download_yaml(COMPANY_IDS_URL)
    companies = company_data["company_identifiers"]
    print(f"  {len(companies)} company identifiers")

    ad_type_data = download_yaml(AD_TYPES_URL)
    ad_types = ad_type_data["ad_types"]
    print(f"  {len(ad_types)} AD types")

    cpp_content = generate_cpp(companies, ad_types)

    output = os.path.abspath(OUTPUT_PATH)
    with open(output, "w", encoding="utf-8") as f:
        f.write(cpp_content)

    print(f"Generated: {output}")
    print("Done. Rebuild the project to pick up the new data.")


if __name__ == "__main__":
    main()
